apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: adding-capabilities-strict
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
  validations:
    - expression: "object.spec.containers.all(container, !has(container.securityContext) || \
                   !has(container.securityContext.capabilities) || \
                   !has(container.securityContext.capabilities.add) || \
                   ((size(container.securityContext.capabilities.add) == 1) && (container.securityContext.capabilities.add[0] == 'NET_BIND_SERVICE')))"
      message: "Any capabilities added other than NET_BIND_SERVICE are disallowed."
    
    - expression: "!has(object.spec.initContainers) || \
                   object.spec.initContainers.all(container, !has(container.securityContext) || \
                   !has(container.securityContext.capabilities) || \
                   !has(container.securityContext.capabilities.add) || \
                   ((size(container.securityContext.capabilities.add) == 1) && (container.securityContext.capabilities.add[0] == 'NET_BIND_SERVICE')))"
      message: "Any capabilities added other than NET_BIND_SERVICE are disallowed."
    
    - expression: "!has(object.spec.ephemeralContainers) || \
                   object.spec.ephemeralContainers.all(container, !has(container.securityContext) || \
                   !has(container.securityContext.capabilities) || \
                   !has(container.securityContext.capabilities.add) || \
                   ((size(container.securityContext.capabilities.add) == 1) && (container.securityContext.capabilities.add[0] == 'NET_BIND_SERVICE')))"
      message: "Any capabilities added other than NET_BIND_SERVICE are disallowed."
